In [1]:
import numpy as np
import pandas as pd
from lightfm import LightFM
import itertools
from lightfm.evaluation import precision_at_k
from scipy.sparse import csr_matrix, lil_matrix, coo_matrix
from time import time

/Users/harlanhutton/opt/anaconda3/lib/python3.8/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(


In [ ]:
def create_interactions(train, test, val):
    
    #train.columns = [0,1,2]
    train_interaction = pd.pivot_table(train, index='user_id_numer', columns='track_id_numer', values='count')
    train_interaction = train_interaction.fillna(0)
    
    #test.columns = [0,1,2]
    test_interaction = pd.pivot_table(test, index='user_id_numer', columns='track_id_numer', values='count')
    test_interaction = test_interaction.fillna(0)
    
    #val.columns = [0,1,2]
    val_interaction = pd.pivot_table(val, index='user_id_numer', columns='track_id_numer', values='count')
    val_interaction = val_interaction.fillna(0)
    
    return train_interaction, test_interaction, val_interaction  

In [ ]:
def create_matrix(train_interaction, test_interaction, val_interaction):
    
    return csr_matrix(train_interaction.values), csr_matrix(test_interaction.values), csr_matrix(val_interaction.values)

In [ ]:
def sample_hyperparameters():
    """
    Yield possible hyperparameter choices.
    """
    
    while True:
        yield {
            "no_components": [5,10,15,20],
            "learning_rate": [.01,.1,1]
        }

In [ ]:
def random_search(train, val, m_iter):

    for hyperparams in itertools.islice(sample_hyperparameters(), num_samples):

        model = LightFM(**hyperparams)
        model.fit(train, epochs=m_iter)

        MAP = precision_at_k(model, val).mean()

        yield (MAP, hyperparams, model)

In [ ]:
def train_model(train_matrix, rank, reg, m_iter):
    
    model = LightFM(random_state = 123, learning_rate = reg, no_components = rank)
    model = model.fit(train_matrix, epochs = m_iter)
    
    return model

In [ ]:
def test_model(model, test_matrix):
    
    return precision_at_k(model, val).mean()

In [ ]:
def main():
    
    train_df = pd.read_csv('data/train_df.csv')
    test_df = pd.read_csv('data/test_df.csv')
    val_df = pd.read_csv('data/val_df.csv')
    
    train_interaction, test_interaction, val_interaction = create_interactions(train_df, test_df, val_df)
#     train_matrix, test_matrix, val_matrix = create_matrix(train_interaction, test_interaction, val_interaction)
    
#     st = time()
#     (score, hyperparams, model) = max(random_search(train_matrix, val_matrix, m_iter = 4), key=lambda x: x[0])
#     end = round(time()-st, 3)
    
#     print("Best score {} at {}".format(score, hyperparams))
#     print("Hyperparameter tuning took {}".format(end))
    
#     st = time()
#     model = train_model(train_model, **hyperparams, m_iter = 4)
#     bestMAP = test_model(model, test_matrix)  
#     end = round(time()-st, 3)
    
#     print("Best MAP on test data: {}".format(bestMAP))
#     print("Final model training and fitting took {}".format(end))
    

In [2]:
train_df = pd.read_csv('data/train_df.csv')

In [10]:
val_df = pd.read_csv('data/val_df.csv')

In [11]:
val_df.shape

(1328, 3)

In [ ]:
rows, r_pos = np.unique(train_df.user_id_numer, return_inverse=True)
cols, c_pos = np.unique(train_df.track_id_numer, return_inverse=True)

In [ ]:
data = train_df.count
row = train_df.user_id_numer
col = train_df.track_id_numer

mat = coo_matrix((data, (row, col)), shape = (len(rows), len(cols)))

In [ ]:
train_interaction = pd.pivot_table(train_df, index='user_id_numer', columns='track_id_numer', values='count', fill_value=0)

In [ ]:
train_interaction

In [3]:
rows, r_pos = np.unique(train_df.user_id_numer, return_inverse=True)
cols, c_pos = np.unique(train_df.track_id_numer, return_inverse=True)

pivot_table = np.zeros((len(rows), len(cols)))
pivot_table[r_pos, c_pos] = 1

print(pivot_table)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
np.unique(train_df.user_id_numer, return_inverse=True)

(array([0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 3.34911e+05,
        3.34912e+05, 3.34913e+05]),
 array([274482,  15107,  25385, ...,  47513, 192557,  28813]))

In [ ]:
s = coo_matrix(pivot_table)

In [ ]:
csr_matrix(pivot_table)

In [ ]:
model = LightFM(random_state = 123, learning_rate = 0.1, no_components = 10)
model = model.fit(pivot_table, epochs = 4)

In [ ]:
# Convert the dense pivot table to a sparse matrix
s = csr_matrix(pivot_table)

In [ ]:
train_df.groupby(['user_id_numer', 'track_id_numer']).size().unstack(fill_value=0)

In [ ]:
val_df = pd.read_csv('data/val_df.csv')

In [ ]:
train_mat = coo_matrix(train_df)

In [ ]:
val_mat = coo_matrix(val_df)

In [ ]:
from scipy.sparse import coo_matrix

In [4]:
model = LightFM(random_state = 123, learning_rate = 0.1, no_components = 10)
model = model.fit(pivot_table, epochs = 4)

AttributeError: 'numpy.ndarray' object has no attribute 'tocoo'

In [ ]:
MAP = precision_at_k(model, val_mat).mean()

In [ ]:
print(MAP)

In [ ]:
val_mat

In [ ]:
train_mat